# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: MLCAS2022 Soybean Pod Counting Challenge
short_description: Soybean pod counting challenge for MLCAS2022
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras egestas a libero nec sagittis.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2022-07-11 05:00:00
end_date: 2022-09-01 04:59:59
published: False

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["RMSE", "MAE", "R2_Score"],
        "default_order_by": "RMSE",
        "metadata": {
          "RMSE": {
            "sort_ascending": True,
            "description": "Root Mean Square Error",
          },
          "MAE": {
            "sort_ascending": True,
            "description": "Mean Absolute Error",
          },
          "R2_Score": {
            "sort_ascending": True,
            "description": "R2 Score",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2022-07-11 05:00:00
    end_date: 2022-08-24 04:59:59
    test_annotation_file: annotations/test_annotations_devsplit.csv
    codename: dev
    max_submissions_per_day: 99
    max_submissions_per_month: 9999
    max_submissions: 9999
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
        required: False
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
        required: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".csv"
  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-08-24 05:00:00
    end_date: 2022-09-01 04:59:59
    test_annotation_file: annotations/test_annotations_testsplit.csv
    codename: test
    max_submissions_per_day: 99
    max_submissions_per_month: 9999
    max_submissions: 9999
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
